### ISSUE TITLE
Prototype adjustments for style and new themes

### ISSUE THREAD

**Issue by matedyl** [Esser50K/90sYouTube#2]
- [x] new pastel colors, remove the saturated colors
- [x] new font, more 90s style
- [x] remove the bevel borders and make it more like material-ui
- [x] remove the burger menu button
- [x] ~~add possibility for switching between dark/light mode on watch page~~

From 2/6/22 meeting:
- [x] add all new styles to src/themes/ and load them dynamically

**Comment by matedyl** [comment]
@Esser50K what do you think about these two?

![image](https://user-images.githubusercontent.com/6464193/171036275-4c22a5aa-f77a-4c34-a33c-4efc2dc177ab.png)
Kongtext + Sans Cullotes

![image](https://user-images.githubusercontent.com/6464193/171036493-f4950813-b8af-45ef-987e-699f6da9ee0a.png)
Kongtext + Andala Script

**Comment by Esser50K** [comment]
I like the second one better because of the bold shadow I think.
You could try with these ones too:
- [border font](https://www.dafont.com/border.font?text=YouTube&psize=l)
- (pixel font)[https://www.1001fonts.com/karmatic-arcade-font.html] <- this one is free for commercial use and I like it a lot.

I also like [this one](https://www.dafont.com/retrolight.font) but not for that specific title, but it resembles the style seen in [this](https://image.spreadshirtmedia.net/image-server/v1/mp/products/T1459A839MPA4459PT28D192978848FS1458/views/1,width=1200,height=1200,appearanceId=839,backgroundColor=F2F2F2/retro-aesthetic-90s-vibe-vintage-sticker.jpg)
Also generally found really good candidates with this query on this site: https://www.1001fonts.com/retro+pixel-fonts.html generally for the other fonts and there are plenty that are free for commercial use

**Comment by matedyl** [comment]
> Also I just crossed out the `add possibility for switching between dark/light mode on watch page` point. I think we can just keep it with black background and white font for now. I opened another issue with all the things I'd like for the Watch page in the end just for reference. But this issue comes first.

Got it


> I like the second one better because of the bold shadow I think. You could try with these ones too:
> 
>     * [border font](https://www.dafont.com/border.font?text=YouTube&psize=l)
> 
>     * (pixel font)[https://www.1001fonts.com/karmatic-arcade-font.html] <- this one is free for commercial use and I like it a lot.
> 
> 
> I also like [this one](https://www.dafont.com/retrolight.font) but not for that specific title, but it resembles the style seen in [this](https://image.spreadshirtmedia.net/image-server/v1/mp/products/T1459A839MPA4459PT28D192978848FS1458/views/1,width=1200,height=1200,appearanceId=839,backgroundColor=F2F2F2/retro-aesthetic-90s-vibe-vintage-sticker.jpg) Also generally found really good candidates with this query on this site: https://www.1001fonts.com/retro+pixel-fonts.html generally for the other fonts and there are plenty that are free for commercial use

![image](https://user-images.githubusercontent.com/6464193/171145416-53d1cfc4-9a59-4223-8c53-9dae322d8833.png)
Karmatic + Border

![image](https://user-images.githubusercontent.com/6464193/171145490-120a8636-d60c-4484-a1d1-cf6acdc730d6.png)
Karmatic + Andala Script

@Esser50K Could you schedule another call using my schedulink to agree on the style direction? 🤙 

So far I've gathered the results of [style ideation in figma](https://www.figma.com/file/xwvuRE0trycIoUbO7Ge7gt/90s-YouTube?node-id=21%3A167). You can also find the new logotype varations there!

**Comment by matedyl** [comment]
Moved some of the checklist items to separate issues: #6 #7 #8 #9
